### PR TITLE
add elixir implementation

### PR DESCRIPTION
**Pull request by mymindishazel**
Heya!
I implemented age in Elixir, since I couldn't find an existing library that does so. It uses libsodium and Erlangs inbuilt crypto module.
Source is [here](https://ravy.dev/root/age_ex). It's published on hex as `age` and has [docs](https://hexdocs.pm/age/) there as well. I've marked it as beta since it only implements basic functionality and X25519 identities. Would love to do full compatibility soon though.

### CODE REVIEW

**Comment by FiloSottile** [comment]
Awesome! age is specifically designed to be easy to implement on top of libsodium.

Are you using https://c2sp.org/CCTV/age? If not, anything I can do to make them more useful? (You can easily skip the ones that require features you don't support.)

**Comment by mymindishazel** [comment]
Currently not using them -- I did try them for debugging purposes, but in my lib it's currently intentionally not possible to e.g. "inject" a file key or any of the ephemeral parameters into the library, so I can't directly use them for automated tests.

I think the test set is cool, but I'm not sure how test-able most of the things are, given a lot of things inherently require randomness. Maybe one could use an exact-content-agnostic way to verify the format of the output (e.g. expected length and format of the chunks) and then just encrypt/decrypt some actual values with test identities, or on a more out-there note, do stuff like automatic statistical analysis for identity generation. I've personally just used the cli tool as a reference for now.

**Comment by mymindishazel** [comment]
One thing I was wondering -- is the ascii armoring part considered integral to age? I made a separate library for it in elixir called [`pem`](https://hexdocs.pm/pem/), which also includes a `strict` toggle to fulfill all the strict parsing requirements in the spec. Should that be part of the library? Should it just be linked there? Should it be part of this listing? Let me know your thoughts :)

**Comment by FiloSottile** [comment]
Oh you don't need to inject anything! Just decrypt the files using the `identity` in the header, and make sure you only get ok if `expect` is `success`, and if so that it decrypts to what's in `payload`. Skip the ones with a `passphrase`. `file key` is there just for debugging.

I think a separate PEM library with a strict mode makes sense and would be good to link from your library and from here. And, you can test it with the `armored` test vectors :)

**Comment by FiloSottile** [comment]
Merging as experimental, but would still very much like to encourage you to integrate the CCTV decryption tests :)

Thank you for building this!

**Pull request merged**
